project:
  type: book
  output-dir: docs

book:
  title: "Da neofita della programmazione funzionale a campione"
  subtitle: "Corso di teoria e pratica per programmatori e non"
  author: 
    - name: "Antonio Montano"
      affiliations:
        - "4M4, Italy"
  date: "8/15/2024"
  version: "0.23"
  status: "Bozza"
  page-navigation: true
  favicon: red-python-logo.png
  search: true
  repo-url: https://github.com/antomon/corso-programmazione-funzionale
  issue-url: https://github.com/antomon/corso-programmazione-funzionale/issues/new/choose
  repo-actions: [edit, source, issue]
  downloads: [pdf, epub]
  sharing: [twitter, linkedin, facebook]
  license: "CC BY-NC-ND"
  navbar:
    search: true
    left:
      - icon: "house-fill"
        href: index.qmd
      - text: "4M4"
        href: "https://4m4.it/"
  chapters:
    - index.qmd
    - part: prima-parte-teoria-categorie.qmd
      chapters: 
        - prima-parte-categorie.qmd
  appendices:
    - appendice-riferimenti.qmd
  page-footer:
    center: 
      - text: "4m4"
        href: "https://4m4.it"

copyright: 
  holder: Antonio Montano
  year: 2024

bibliography: references.bib
csl: iso690-author-date-it.csl

lang: it

format:
  html:
    theme:
      light: [pulse, theme-light.scss]
      dark: [pulse, theme-dark.scss]
    code-line-numbers: true
    reference-location: margin
    citation-location: margin
    toc-depth: 4
  pdf:
    documentclass: scrbook
    geometry: "left=1.5cm,right=1.5cm,top=2cm,bottom=2cm"
    code-line-numbers: true
    reference-location: block
    citation-location: block
    toc-depth: 4
  epub:
    code-line-numbers: true
    reference-location: block
    citation-location: block
    toc-depth: 4

comments:
  hypothesis: true



